// DOM KeyboardEvent.code -> libretro RETROK_* 値 のマッピング
// 値は px68k-libretro/libretro-common/include/libretro.h の retro_key enum に基づく

export const RETROK = {
  UNKNOWN: 0,
  BACKSPACE: 8,
  TAB: 9,
  CLEAR: 12,
  RETURN: 13,
  PAUSE: 19,
  ESCAPE: 27,
  SPACE: 32,
  EXCLAIM: 33,
  QUOTEDBL: 34,
  HASH: 35,
  DOLLAR: 36,
  AMPERSAND: 38,
  QUOTE: 39,
  LEFTPAREN: 40,
  RIGHTPAREN: 41,
  ASTERISK: 42,
  PLUS: 43,
  COMMA: 44,
  MINUS: 45,
  PERIOD: 46,
  SLASH: 47,
  0: 48,
  1: 49,
  2: 50,
  3: 51,
  4: 52,
  5: 53,
  6: 54,
  7: 55,
  8: 56,
  9: 57,
  COLON: 58,
  SEMICOLON: 59,
  LESS: 60,
  EQUALS: 61,
  GREATER: 62,
  QUESTION: 63,
  AT: 64,
  LEFTBRACKET: 91,
  BACKSLASH: 92,
  RIGHTBRACKET: 93,
  CARET: 94,
  UNDERSCORE: 95,
  BACKQUOTE: 96,
  a: 97,
  b: 98,
  c: 99,
  d: 100,
  e: 101,
  f: 102,
  g: 103,
  h: 104,
  i: 105,
  j: 106,
  k: 107,
  l: 108,
  m: 109,
  n: 110,
  o: 111,
  p: 112,
  q: 113,
  r: 114,
  s: 115,
  t: 116,
  u: 117,
  v: 118,
  w: 119,
  x: 120,
  y: 121,
  z: 122,
  DELETE: 127,
  KP0: 256,
  KP1: 257,
  KP2: 258,
  KP3: 259,
  KP4: 260,
  KP5: 261,
  KP6: 262,
  KP7: 263,
  KP8: 264,
  KP9: 265,
  KP_PERIOD: 266,
  KP_DIVIDE: 267,
  KP_MULTIPLY: 268,
  KP_MINUS: 269,
  KP_PLUS: 270,
  KP_ENTER: 271,
  KP_EQUALS: 272,
  UP: 273,
  DOWN: 274,
  RIGHT: 275,
  LEFT: 276,
  INSERT: 277,
  HOME: 278,
  END: 279,
  PAGEUP: 280,
  PAGEDOWN: 281,
  F1: 282,
  F2: 283,
  F3: 284,
  F4: 285,
  F5: 286,
  F6: 287,
  F7: 288,
  F8: 289,
  F9: 290,
  F10: 291,
  F11: 292,
  F12: 293,
  F13: 294,
  F14: 295,
  F15: 296,
  NUMLOCK: 300,
  CAPSLOCK: 301,
  SCROLLOCK: 302,
  RSHIFT: 303,
  LSHIFT: 304,
  RCTRL: 305,
  LCTRL: 306,
  RALT: 307,
  LALT: 308,
  RMETA: 309,
  LMETA: 310,
  LSUPER: 311,
  RSUPER: 312,
  MODE: 313,
  COMPOSE: 314,
  HELP: 315,
  PRINT: 316,
  SYSREQ: 317,
  BREAK: 318,
  MENU: 319,
  POWER: 320,
  EURO: 321,
  UNDO: 322,
  OEM_102: 323,
  BROWSER_BACK: 324,
  BROWSER_FORWARD: 325,
  BROWSER_REFRESH: 326,
  BROWSER_STOP: 327,
  BROWSER_SEARCH: 328,
  BROWSER_FAVORITES: 329,
  BROWSER_HOME: 330,
  VOLUME_MUTE: 331,
} as const;

/**
 * libretroのRETROKからX68000キーボードのスキャンコードへの対応表。
 * px68k-libretro/libretro.cのKeyTableと同じ内容をホスト側にも持つ。
 * RETROK_0はコア表に0x0b/0x34の重複があるため、通常の数字0として先に送られる0x0bを採用する。
 */
export const RETROK_TO_SCANCODE: Readonly<Record<number, number>> = {
  [RETROK.ESCAPE]: 0x01,
  [RETROK[1]]: 0x02,
  [RETROK[2]]: 0x03,
  [RETROK[3]]: 0x04,
  [RETROK[4]]: 0x05,
  [RETROK[5]]: 0x06,
  [RETROK[6]]: 0x07,
  [RETROK[7]]: 0x08,
  [RETROK[8]]: 0x09,
  [RETROK[9]]: 0x0a,
  [RETROK[0]]: 0x0b,
  [RETROK.MINUS]: 0x0c,
  [RETROK.EQUALS]: 0x0d,
  [RETROK.BACKSLASH]: 0x0e,
  [RETROK.BACKSPACE]: 0x0f,
  [RETROK.TAB]: 0x10,
  [RETROK.q]: 0x11,
  [RETROK.w]: 0x12,
  [RETROK.e]: 0x13,
  [RETROK.r]: 0x14,
  [RETROK.t]: 0x15,
  [RETROK.y]: 0x16,
  [RETROK.u]: 0x17,
  [RETROK.i]: 0x18,
  [RETROK.o]: 0x19,
  [RETROK.p]: 0x1a,
  [RETROK.BACKQUOTE]: 0x1b,
  [RETROK.LEFTBRACKET]: 0x1c,
  [RETROK.RETURN]: 0x1d,
  [RETROK.a]: 0x1e,
  [RETROK.s]: 0x1f,
  [RETROK.d]: 0x20,
  [RETROK.f]: 0x21,
  [RETROK.g]: 0x22,
  [RETROK.h]: 0x23,
  [RETROK.j]: 0x24,
  [RETROK.k]: 0x25,
  [RETROK.l]: 0x26,
  [RETROK.SEMICOLON]: 0x27,
  [RETROK.QUOTE]: 0x28,
  [RETROK.RIGHTBRACKET]: 0x29,
  [RETROK.z]: 0x2a,
  [RETROK.x]: 0x2b,
  [RETROK.c]: 0x2c,
  [RETROK.v]: 0x2d,
  [RETROK.b]: 0x2e,
  [RETROK.n]: 0x2f,
  [RETROK.m]: 0x30,
  [RETROK.COMMA]: 0x31,
  [RETROK.PERIOD]: 0x32,
  [RETROK.SLASH]: 0x33,
  [RETROK.SPACE]: 0x35,
  [RETROK.HOME]: 0x36,
  [RETROK.DELETE]: 0x37,
  [RETROK.PAGEDOWN]: 0x38,
  [RETROK.PAGEUP]: 0x39,
  [RETROK.END]: 0x3a,
  [RETROK.LEFT]: 0x3b,
  [RETROK.UP]: 0x3c,
  [RETROK.RIGHT]: 0x3d,
  [RETROK.DOWN]: 0x3e,
  [RETROK.CLEAR]: 0x3f,
  [RETROK.KP_DIVIDE]: 0x40,
  [RETROK.KP_MULTIPLY]: 0x41,
  [RETROK.KP_MINUS]: 0x42,
  [RETROK.KP7]: 0x43,
  [RETROK.KP8]: 0x44,
  [RETROK.KP9]: 0x45,
  [RETROK.KP_PLUS]: 0x46,
  [RETROK.KP4]: 0x47,
  [RETROK.KP5]: 0x48,
  [RETROK.KP6]: 0x49,
  [RETROK.KP_EQUALS]: 0x4a,
  [RETROK.KP1]: 0x4b,
  [RETROK.KP2]: 0x4c,
  [RETROK.KP3]: 0x4d,
  [RETROK.KP_ENTER]: 0x4e,
  [RETROK.KP0]: 0x4f,
  [RETROK.KP_PERIOD]: 0x51,
  [RETROK.PRINT]: 0x52,
  [RETROK.SCROLLOCK]: 0x53,
  [RETROK.F11]: 0x54,
  [RETROK.EURO]: 0x55,
  [RETROK.UNDO]: 0x56,
  [RETROK.OEM_102]: 0x57,
  [RETROK.BROWSER_BACK]: 0x58,
  [RETROK.BROWSER_FORWARD]: 0x59,
  [RETROK.BROWSER_REFRESH]: 0x5a,
  [RETROK.BROWSER_STOP]: 0x5b,
  [RETROK.BROWSER_SEARCH]: 0x5c,
  [RETROK.CAPSLOCK]: 0x5d,
  [RETROK.INSERT]: 0x5e,
  [RETROK.BROWSER_FAVORITES]: 0x5f,
  [RETROK.BROWSER_HOME]: 0x60,
  [RETROK.BREAK]: 0x61,
  [RETROK.PAUSE]: 0x61,
  [RETROK.VOLUME_MUTE]: 0x62,
  [RETROK.F1]: 0x63,
  [RETROK.F2]: 0x64,
  [RETROK.F3]: 0x65,
  [RETROK.F4]: 0x66,
  [RETROK.F5]: 0x67,
  [RETROK.F6]: 0x68,
  [RETROK.F7]: 0x69,
  [RETROK.F8]: 0x6a,
  [RETROK.F9]: 0x6b,
  [RETROK.F10]: 0x6c,
  [RETROK.LSHIFT]: 0x70,
  [RETROK.RSHIFT]: 0x70,
  [RETROK.LCTRL]: 0x71,
  [RETROK.RCTRL]: 0x71,
  [RETROK.LSUPER]: 0x72,
  [RETROK.LALT]: 0x72,
  [RETROK.RSUPER]: 0x73,
  [RETROK.RALT]: 0x73,
};

// KeyboardEvent.code (物理キー位置) -> RETROK
export const CODE_TO_RETROK: Record<string, number> = {
  // 英字
  KeyA: RETROK.a, KeyB: RETROK.b, KeyC: RETROK.c, KeyD: RETROK.d,
  KeyE: RETROK.e, KeyF: RETROK.f, KeyG: RETROK.g, KeyH: RETROK.h,
  KeyI: RETROK.i, KeyJ: RETROK.j, KeyK: RETROK.k, KeyL: RETROK.l,
  KeyM: RETROK.m, KeyN: RETROK.n, KeyO: RETROK.o, KeyP: RETROK.p,
  KeyQ: RETROK.q, KeyR: RETROK.r, KeyS: RETROK.s, KeyT: RETROK.t,
  KeyU: RETROK.u, KeyV: RETROK.v, KeyW: RETROK.w, KeyX: RETROK.x,
  KeyY: RETROK.y, KeyZ: RETROK.z,

  // 数字
  Digit0: RETROK[0], Digit1: RETROK[1], Digit2: RETROK[2], Digit3: RETROK[3],
  Digit4: RETROK[4], Digit5: RETROK[5], Digit6: RETROK[6], Digit7: RETROK[7],
  Digit8: RETROK[8], Digit9: RETROK[9],

  // 記号
  Minus: RETROK.MINUS,
  Equal: RETROK.EQUALS,
  BracketLeft: RETROK.LEFTBRACKET,
  BracketRight: RETROK.RIGHTBRACKET,
  Backslash: RETROK.BACKSLASH,
  Semicolon: RETROK.SEMICOLON,
  Quote: RETROK.QUOTE,
  Backquote: RETROK.BACKQUOTE,
  Comma: RETROK.COMMA,
  Period: RETROK.PERIOD,
  Slash: RETROK.SLASH,
  IntlYen: RETROK.BACKSLASH,
  IntlRo: RETROK.UNDERSCORE,

  // 制御
  Enter: RETROK.RETURN,
  Space: RETROK.SPACE,
  Escape: RETROK.ESCAPE,
  Backspace: RETROK.BACKSPACE,
  Tab: RETROK.TAB,
  CapsLock: RETROK.CAPSLOCK,
  KanaMode: RETROK.BROWSER_REFRESH,
  ShiftLeft: RETROK.LSHIFT,
  ShiftRight: RETROK.RSHIFT,
  ControlLeft: RETROK.LCTRL,
  ControlRight: RETROK.RCTRL,
  AltLeft: RETROK.LALT,
  AltRight: RETROK.RALT,
  MetaLeft: RETROK.LMETA,
  MetaRight: RETROK.RMETA,
  ContextMenu: RETROK.MENU,
  Insert: RETROK.INSERT,
  Delete: RETROK.DELETE,
  Home: RETROK.HOME,
  End: RETROK.END,
  PageUp: RETROK.PAGEUP,
  PageDown: RETROK.PAGEDOWN,
  PrintScreen: RETROK.PRINT,
  ScrollLock: RETROK.SCROLLOCK,
  Pause: RETROK.PAUSE,
  NumLock: RETROK.NUMLOCK,

  // 矢印
  ArrowUp: RETROK.UP,
  ArrowDown: RETROK.DOWN,
  ArrowLeft: RETROK.LEFT,
  ArrowRight: RETROK.RIGHT,

  // ファンクションキー
  F1: RETROK.F1, F2: RETROK.F2, F3: RETROK.F3, F4: RETROK.F4,
  F5: RETROK.F5, F6: RETROK.F6, F7: RETROK.F7, F8: RETROK.F8,
  F9: RETROK.F9, F10: RETROK.F10, F11: RETROK.F11, F12: RETROK.F12,

  // テンキー
  Numpad0: RETROK.KP0, Numpad1: RETROK.KP1, Numpad2: RETROK.KP2,
  Numpad3: RETROK.KP3, Numpad4: RETROK.KP4, Numpad5: RETROK.KP5,
  Numpad6: RETROK.KP6, Numpad7: RETROK.KP7, Numpad8: RETROK.KP8,
  Numpad9: RETROK.KP9,
  NumpadDecimal: RETROK.KP_PERIOD,
  NumpadDivide: RETROK.KP_DIVIDE,
  NumpadMultiply: RETROK.KP_MULTIPLY,
  NumpadSubtract: RETROK.KP_MINUS,
  NumpadAdd: RETROK.KP_PLUS,
  NumpadEnter: RETROK.KP_ENTER,
  NumpadEqual: RETROK.KP_EQUALS,
};

export function codeToRetrok(code: string): number {
  return CODE_TO_RETROK[code] ?? RETROK.UNKNOWN;
}

// --- ASCII 文字 → X68000(JIS配列)のキー入力 -------------------------------
// MCP ブリッジの type_text 用。px68k の KeyTable(libretro.c)は「物理キー」の RETROK しか
// 持たないため、'!' のような記号は SHIFT + 元キーに分解して送る必要がある。
// 配列は X68000 の JIS 準拠(数字段の右端が ^ と ¥、'@' は P の右、':' は ; の右)。

/** SHIFT 無しで打てる文字 */
const PLAIN_KEYS: Record<string, number> = {
  ' ': RETROK.SPACE,
  '\n': RETROK.RETURN,
  '\r': RETROK.RETURN,
  '\t': RETROK.TAB,
  '-': RETROK.MINUS,
  '^': RETROK.EQUALS,
  '\\': RETROK.BACKSLASH,
  '@': RETROK.BACKQUOTE,
  '[': RETROK.LEFTBRACKET,
  ']': RETROK.RIGHTBRACKET,
  ';': RETROK.SEMICOLON,
  ':': RETROK.QUOTE,
  ',': RETROK.COMMA,
  '.': RETROK.PERIOD,
  '/': RETROK.SLASH,
};

/** SHIFT を伴う文字 → 元キー */
const SHIFTED_KEYS: Record<string, number> = {
  '!': RETROK[1],
  '"': RETROK[2],
  '#': RETROK[3],
  $: RETROK[4],
  '%': RETROK[5],
  '&': RETROK[6],
  "'": RETROK[7],
  '(': RETROK[8],
  ')': RETROK[9],
  '=': RETROK.MINUS,
  '~': RETROK.EQUALS,
  '|': RETROK.BACKSLASH,
  '`': RETROK.BACKQUOTE,
  '{': RETROK.LEFTBRACKET,
  '}': RETROK.RIGHTBRACKET,
  '+': RETROK.SEMICOLON,
  '*': RETROK.QUOTE,
  '<': RETROK.COMMA,
  '>': RETROK.PERIOD,
  '?': RETROK.SLASH,
};

export interface TypedKey {
  code: number;
  shift: boolean;
}

/**
 * ASCII 文字を1つ、押すべきキーへ変換する。対応していない文字は null。
 * 全角文字は非対応(X68000 側の FEP を経由しないと入力できないため)。
 */
export function charToKey(ch: string): TypedKey | null {
  if (ch >= 'a' && ch <= 'z') return { code: ch.charCodeAt(0), shift: false };
  if (ch >= 'A' && ch <= 'Z') return { code: ch.toLowerCase().charCodeAt(0), shift: true };
  if (ch >= '0' && ch <= '9') return { code: ch.charCodeAt(0), shift: false };
  if (ch in PLAIN_KEYS) return { code: PLAIN_KEYS[ch], shift: false };
  if (ch in SHIFTED_KEYS) return { code: SHIFTED_KEYS[ch], shift: true };
  return null;
}
